version: '3.4'

services:

#### Stats App

  stats-cache:
    image: redis:5-alpine
    networks:
     - mynet
  stats-queue:
    image: rabbitmq:3-alpine
    networks:
     - mynet
  # Wait for RabbitMQ to be joinable.
  check-queue-start: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - stats-queue
    command: 'dockerize -wait=amqp://stats-queue:5672'
  stats-api:
    image: mindarodev.azurecr.io/samples/stats-api:v7
    build:
      context: ../
      dockerfile: ./stats-api/Dockerfile
    depends_on: 
      - check-queue-start
      - stats-cache
    networks:
     - mynet
  stats-worker:
    image: mindarodev.azurecr.io/samples/stats-worker:v7
    build:
      context: ../
      dockerfile: ./stats-worker/Dockerfile
    depends_on: 
      - check-queue-start
      - stats-cache
      - stats-api
    networks:
     - mynet

#### Todo App

  mongodb:
    image: mongo:4
    networks:
     - mynet
  todo-api:
    image: ${DOCKER_REGISTRY-}shankarvrp/todoapi
    build:
      context: ../
      dockerfile: ./database-api/Dockerfile
    depends_on: 
      - check-queue-start
      - stats-cache
      - stats-api
      - todo-db 
    networks:
     - mynet
    volumes:
      - logvol:/app/logs
  todo-app:
    image: ${DOCKER_REGISTRY-}shankarvrp/todoapp
    build:
      context: ../
      dockerfile: ./frontend/Dockerfile
    depends_on: 
      - check-queue-start
      - stats-cache
      - stats-api
      - todo-db    
      - todo-api 
    networks:
     - mynet
     
networks:
  mynet:
volumes:
  logvol: